In [1]:
import numpy as np
import pandas as pd

In [2]:
# Generate random data
data = {
    "ID": np.arange(1, 31),
    "Name": np.random.choice(["Alice", "Bob", "Charlie", "David", "Eve"], size=30),
    "Age": np.random.randint(20, 60, size=30),
    "Salary": np.random.uniform(30000, 120000, size=30).round(2),
    "Department": np.random.choice(["HR", "Finance", "IT", "Marketing"], size=30),
    "Join_Date": pd.date_range(start="2020-01-01", periods=30, freq="ME"),
    "Is_Manager": np.random.choice([True, False], size=30),
    "Performance_Score": np.random.randint(1, 6, size=30),
    "Bonus": np.where(np.random.rand(30) > 0.7, np.random.uniform(500, 5000, size=30).round(2), np.nan)  # Some NaN values
}

# Create DataFrame
df = pd.DataFrame(data)
print(df.shape)
df.head()

(30, 9)

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,29,110997.65,Finance,2020-01-31,False,3,NaN
1,2,Alice,37,37024.24,Finance,2020-02-29,False,3,1628.62
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
3,4,David,39,32376.57,IT,2020-04-30,False,4,1950.48
4,5,Eve,32,30162.56,IT,2020-05-31,False,5,4657.09

In [3]:
# How do you install Pandas?
# How do you import Pandas in Python?
# How do you create a Pandas Series?
# How do you create a Pandas DataFrame from a dictionary?
# How do you read a CSV file into a Pandas DataFrame?
# How do you display the first 5 rows of a DataFrame?

In [4]:
# How do you get the column names of a DataFrame
columns1 = pd.Series(df.columns)
columns2 = df.columns
columns3 = df.columns.tolist()
# print(columns1)
# print(columns2)
print(columns3)

['ID', 'Name', 'Age', 'Salary', 'Department', 'Join_Date', 'Is_Manager', 'Performance_Score', 'Bonus']

In [5]:
# How do you check for missing values in a DataFrame
missing_values = df.isnull().sum()
missing_values

ID                    0
Name                  0
Age                   0
Salary                0
Department            0
Join_Date             0
Is_Manager            0
Performance_Score     0
Bonus                16
dtype: int64

In [6]:
# How do you check for missing values of a particular in a DataFrame
missing_values = df['Age'].isnull().sum()
missing_values

0

In [7]:
# How do you fill missing values with a specific value
fill_missing_values = df["Age"].fillna(0)
fill_missing_values[:3]

0    29
1    37
2    51
Name: Age, dtype: int64

In [8]:
# How do you fill missing values with a specific value with mean, median and mode
fill_mean_values = df["Age"].fillna(df["Age"].mean())
fill_median_values = df["Age"].fillna(df["Age"].median())
fill_mode_values = df["ID"].fillna(df["ID"].mode()[0])

In [9]:
# How do you drop rows containing missing values
drop_missing_values = df.dropna()
df.shape

(30, 9)

In [10]:
# How do you drop rows containing missing values based on particular column
drop_missing_values = df.dropna(subset=["Age"])
drop_missing_values[:3]

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,29,110997.65,Finance,2020-01-31,False,3,NaN
1,2,Alice,37,37024.24,Finance,2020-02-29,False,3,1628.62
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN

In [ ]:
# How do you delete a particular column
delete_column = df.drop(columns=["Age"])  # Method 2
delete_column = df.pop("Age")             # Method 3

In [11]:
# How do you select a specific column from a DataFrame
select_column = df["Name"]
select_column[:3]

0        Bob
1      Alice
2    Charlie
Name: Name, dtype: object

In [12]:
# How do you select multiple columns from a DataFrame
select_columns = df[["Age", "Name"]]
select_columns[:3]

   Age     Name
0   29      Bob
1   37    Alice
2   51  Charlie

In [13]:
# How do you select rows based on a condition (e.g., age > 30)
select_column = df[df['Salary'] > 100000]
select_column

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,29,110997.65,Finance,2020-01-31,False,3,NaN
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
13,14,Eve,40,108472.43,Marketing,2021-02-28,True,3,NaN
14,15,Eve,27,107483.83,Marketing,2021-03-31,True,2,3958.37
16,17,Bob,36,105839.17,Marketing,2021-05-31,True,4,NaN
24,25,David,57,111924.49,Marketing,2022-01-31,False,4,NaN
27,28,Charlie,51,119042.02,Finance,2022-04-30,True,2,NaN

In [14]:
# How do you select rows based on a condition (e.g., age > 30 and salary > 100000)
multiple_conditions = df[(df["Age"] > 30) & (df["Salary"] > 100000)]
multiple_conditions

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
13,14,Eve,40,108472.43,Marketing,2021-02-28,True,3,NaN
16,17,Bob,36,105839.17,Marketing,2021-05-31,True,4,NaN
24,25,David,57,111924.49,Marketing,2022-01-31,False,4,NaN
27,28,Charlie,51,119042.02,Finance,2022-04-30,True,2,NaN

In [15]:
# How do you filter rows where a column contains a specific value
filtered = df[df['Department'] == 'HR']
filtered[:5]

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
10,11,Alice,55,60356.45,HR,2020-11-30,False,1,605.98
18,19,Eve,58,78779.82,HR,2021-07-31,False,4,2046.15

In [16]:
# How do you filter rows where a column contains a specific value
filtered = df[(df['Department'] == 'HR') & (df['Salary'] > 100000)]
filtered

,ID,Name,Age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN

In [17]:
# How do you get summary statistics (mean, median, std) of a DataFrame
summary = df.describe()
summary

,ID,Age,Salary,Join_Date,Performance_Score,Bonus
count,30.000000,30.000000,30.000000,30,30.000000,14.000000
mean,15.500000,41.166667,75504.523667,2021-04-15 13:36:00,3.100000,2267.068571
min,1.000000,21.000000,30162.560000,2020-01-31 00:00:00,1.000000,605.980000
25%,8.250000,32.000000,54078.357500,2020-09-07 12:00:00,2.000000,970.835000
50%,15.500000,41.000000,78459.705000,2021-04-15 00:00:00,3.000000,1965.385000
75%,22.750000,51.000000,96584.257500,2021-11-22 12:00:00,4.000000,3480.315000
max,30.000000,58.000000,119042.020000,2022-06-30 00:00:00,5.000000,4943.090000
std,8.803408,11.668062,26584.327480,NaN,1.348051,1577.088772

In [18]:
# How do you rename columns in a Pandas DataFrame
df.rename(columns={'Name': 'Gyan', 'Age': 'age'}, inplace=True)
df.head()

,ID,Gyan,age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,29,110997.65,Finance,2020-01-31,False,3,NaN
1,2,Alice,37,37024.24,Finance,2020-02-29,False,3,1628.62
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
3,4,David,39,32376.57,IT,2020-04-30,False,4,1950.48
4,5,Eve,32,30162.56,IT,2020-05-31,False,5,4657.09

In [19]:
# How do you sort a DataFrame by a column
df.sort_values(by='age', ascending=False)
df.head()

,ID,Gyan,age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,29,110997.65,Finance,2020-01-31,False,3,NaN
1,2,Alice,37,37024.24,Finance,2020-02-29,False,3,1628.62
2,3,Charlie,51,101125.03,HR,2020-03-31,False,2,NaN
3,4,David,39,32376.57,IT,2020-04-30,False,4,1950.48
4,5,Eve,32,30162.56,IT,2020-05-31,False,5,4657.09

In [20]:
# How do you reset the index of a DataFrame
# How do you set a specific column as the index of a DataFrame

In [21]:
# How do you check the data types of each column in a DataFrame
summary = df.info()
summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 30 non-null     int64
 1   Gyan               30 non-null     object
 2   age                30 non-null     int64
 3   Salary             30 non-null     float64
 4   Department         30 non-null     object
 5   Join_Date          30 non-null     datetime64[ns]
 6   Is_Manager         30 non-null     bool
 7   Performance_Score  30 non-null     int64
 8   Bonus              14 non-null     float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(3), object(2)
memory usage: 2.0+ KB

In [22]:
# How do you convert a column's data type to a different type (e.g., int → float)
df['age'] = df['age'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 30 non-null     int64
 1   Gyan               30 non-null     object
 2   age                30 non-null     float64
 3   Salary             30 non-null     float64
 4   Department         30 non-null     object
 5   Join_Date          30 non-null     datetime64[ns]
 6   Is_Manager         30 non-null     bool
 7   Performance_Score  30 non-null     int64
 8   Bonus              14 non-null     float64
dtypes: bool(1), datetime64[ns](1), float64(3), int64(2), object(2)
memory usage: 2.0+ KB

In [23]:
# How do you apply a function to each element of a column
df['age'] = df['age'].apply(lambda x: x*2)
df.head()

,ID,Gyan,age,Salary,Department,Join_Date,Is_Manager,Performance_Score,Bonus
0,1,Bob,58.0,110997.65,Finance,2020-01-31,False,3,NaN
1,2,Alice,74.0,37024.24,Finance,2020-02-29,False,3,1628.62
2,3,Charlie,102.0,101125.03,HR,2020-03-31,False,2,NaN
3,4,David,78.0,32376.57,IT,2020-04-30,False,4,1950.48
4,5,Eve,64.0,30162.56,IT,2020-05-31,False,5,4657.09

In [24]:
# How do you group data using groupby()
average_salary = df.groupby("Department")["Salary"].mean()                      # Group by Department and calculate the average salary
grouped_count = df.groupby("Department")["Salary"].count()                      # Count the number of employees in each department
total_salary = df.groupby("Department")["Salary"].sum()                         # Find the total salary per department
aggregations = df.groupby("Department")["Salary"].agg(["mean", "sum", "max"])   # Apply multiple aggregation functions
multiple_sum = df.groupby(["Department", "Is_Manager"])["Salary"].sum()         # Grouping by multiple columns
print("Average Salary:\n", average_salary, '\n')
print("Grouped Count:\n", grouped_count, '\n')
print("Total Salary:\n", total_salary, '\n')
print("Aggregations:\n", aggregations, '\n')
print("Multiple Sum:\n", multiple_sum, '\n')

Average Salary:
 Department
Finance      75456.015714
HR           80087.100000
IT           67227.873000
Marketing    82440.357000
Name: Salary, dtype: float64

Grouped Count:
 Department
Finance       7
HR            3
IT           10
Marketing    10
Name: Salary, dtype: int64

Total Salary:
 Department
Finance      528192.11
HR           240261.30
IT           672278.73
Marketing    824403.57
Name: Salary, dtype: float64

Aggregations:
                     mean        sum        max
Department
Finance     75456.015714  528192.11  119042.02
HR          80087.100000  240261.30  101125.03
IT          67227.873000  672278.73   96827.90
Marketing   82440.357000  824403.57  111924.49

Multiple Sum:
 Department  Is_Manager
Finance     False         339366.14
            True          188825.97
HR          False         240261.30
IT          False         244135.23
            True          428143.50
Marketing   False         264887.23
            True          559516.34
Name: Salary, dtype: float64

In [25]:
# How do you aggregate grouped data using agg()
aggregations = df.groupby("Department")["Salary"].agg(["mean", "sum", "max"])   # Apply multiple aggregation functions
aggregations

                    mean        sum        max
Department
Finance     75456.015714  528192.11  119042.02
HR          80087.100000  240261.30  101125.03
IT          67227.873000  672278.73   96827.90
Marketing   82440.357000  824403.57  111924.49

In [26]:
# How do you get the row with the highest and lowest values in a column
row = df.loc[df['Salary'].idxmax()]
col = df.loc[df['Salary'].idxmin()]

In [27]:
# How do you merge two DataFrames based on a common column (merge())

In [28]:
# How do you concatenate multiple DataFrames (concat())

In [29]:
# How do you remove duplicate rows from a DataFrame
data = {
    "Employee": ["Alice", "Bob", "Charlie", "Alice", "Eve", "Bob"],
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT"],
    "Salary": [50000, 70000, 80000, 50000, 60000, 70000]
}
df = pd.DataFrame(data)
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

  Employee Department  Salary
0    Alice         HR   50000
1      Bob         IT   70000
2  Charlie         IT   80000
4      Eve    Finance   60000

In [30]:
# How do you create a new column based on values of another column
df['New_Salary'] = df['Salary'] * 2
df.head()

  Employee Department  Salary  New_Salary
0    Alice         HR   50000      100000
1      Bob         IT   70000      140000
2  Charlie         IT   80000      160000
3    Alice         HR   50000      100000
4      Eve    Finance   60000      120000

In [31]:
# How do you count the number of occurrences of unique values in a column?
# How do you pivot a DataFrame using pivot_table()?
# How do you reshape data using melt()?
# How do you find correlation between numerical columns?
# How do you apply a lambda function to modify a column?

In [38]:
# How do you shuffle rows of a DataFrame randomly
shuffled_df = df.sample(frac=1).reset_index(drop=True)
shuffled_df

  Employee Department  Salary  New_Salary
0      Eve    Finance   60000      120000
1      Bob         IT   70000      140000
2    Alice         HR   50000      100000
3    Alice         HR   50000      100000
4  Charlie         IT   80000      160000
5      Bob         IT   70000      140000

In [ ]:
# How do you sample N random rows from a DataFrame?
# How do you convert a categorical column to one-hot encoding?
# How do you convert a datetime column to Pandas datetime format?
# How do you extract year, month, and day from a datetime column?
# How do you create a rolling window of size N to calculate moving averages?

In [32]:
# How do you handle outliers in a DataFrame?
# How do you remove highly correlated columns from a DataFrame?
# How do you handle large datasets efficiently in Pandas?
# How do you optimize Pandas DataFrames using category data type?
# How do you efficiently filter rows using .query() instead of loops?
# How do you merge two DataFrames with different column names?
# How do you calculate cumulative sum (cumsum()) in a column?
# How do you convert a Pandas DataFrame to a NumPy array?

In [35]:
# How do you export a Pandas DataFrame to a CSV file
data = df.to_csv('/content/data.csv', index=False)

In [ ]:
# How do you handle missing values using interpolation?